# Introduction to Numpy
 * The fundamental python library for manipulating matrices and arrays

 * Much faster than base Python for computation 

 * Official Docs: https://docs.scipy.org/doc/numpy/reference/index.html.

 
 * If you are coming from Matlab, [here](http://scipy.github.io/old-wiki/pages/NumPy_for_Matlab_Users) is a handy reference comparing the similarities and differences between Matlab and numpy. 

## Contents
### [Introduction to `ndarray`s](#ndarray)
####  [Construction](#constructors)
#### [Reshaping](#reshaping)
#### [Subsetting](#subsetting)
### [A note on copying](#A_Note_on_Copying)
#### [Aggregation](#aggregation)
#### [Array math](#array_math)
#### [Comparisons](#comparisons)
#### [Combining Arrays](#combining)
### [Broadcasting and Vectorization](#broadcasting)


The official documentation for the numpy library can be found at: https://docs.scipy.org/doc/numpy/reference/index.html. You will see that there are many things that you can do with numpy arrays. This module will aim to cover some of the basics as well as provide general guidelines for how to make sure you utilize numpy correctly to take advantage of the underlying optimizations.

Some of you may be much more familiar with Matlab and its associated array data structures. [here](http://scipy.github.io/old-wiki/pages/NumPy_for_Matlab_Users) is a handy reference comparing the similarities and differences between Matlab and numpy. 

In this module, we will cover how to various methods for creating arrays, indexing and slicing them, typing, and performing basic linear algebra computations. In addition, we will introduce the concept of *broadcasting*, which is an important tool avoiding unnecessarily slow `for` loops in python

### Importing Numpy

In [6]:
import numpy as np

<a id=ndarray></a>
## The N-Dimensional Array (`ndarray`) 


The `ndarray` is numpy's fundamental data structure. As the name suggests, it is a single or multidimensional array that contains elements that are of fixed type and size.

In [6]:
example_ndarray = np.array([[1,2,3], [4,5,6], [7,8,9]], dtype = np.float32)
print(example_ndarray)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]]


 Two of the most important attributes of the `ndarray` class is its `shape` and its `dtype`. 

You can access a numpy array's `shape` and `dtype` by simply calling `.shape`and `.dtype`

In [13]:
print('the type of this array is {}'.format( type(example_ndarray )))
print('the shape of this array is {}'.format( example_ndarray.shape ))
print('the dtype of this array is {}'.format( example_ndarray.dtype ))

the type of this array is <class 'numpy.ndarray'>
the shape of this array is (3, 3)
the dtype of this array is float32


In the example above, we created the array using a list of lists. However, there are many other ways to create numpy arrays. Here are some of the more useful constructors

<a id='constructors'></a>
### How to construct an `ndarray` 

In [18]:
np.ones(shape = (3,3), dtype = np.float64)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [15]:
np.zeros(shape = (3,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [5]:
# arange takes start and stop argument, similar to python's range()
np.arange(0,9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [19]:
# linspace creates evenly spaced arrays
np.linspace(0, 9, 20)
np.linspace?

In [23]:
# Draws from a uniform distribution with support [0.0, 1.0)
np.random.random((3,3))

array([[ 0.08395938,  0.45452506,  0.52831819],
       [ 0.84286623,  0.33641653,  0.28309   ],
       [ 0.50697561,  0.50743655,  0.2459022 ]])

In [4]:
np.full((3,3), 17, dtype = np.int16)

array([[17, 17, 17],
       [17, 17, 17],
       [17, 17, 17]], dtype=int16)

In [51]:
# You can also change the dtype of a numpy array by calling astype() or passing the array to np.array and specifying a new dtyps
typed_array = np.ones((3,3), dtype = np.int16)

typed_array.astype(np.float32)

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]], dtype=float32)

In [52]:
np.array(typed_array, np.uint8)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=uint8)

<a id='reshaping'></a>
### Reshaping

Let's say you have an array of size (3,3), but you'd it to actually be (9,1). You can simply call `reshape` with the dimensions that you wish to resize the array to

In [26]:
np.ones((3,3)).reshape(9,1)

array([[ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.]])

In [27]:
# Or even into 3 dimensions
np.ones((4,4)).reshape(2,4,2)

array([[[ 1.,  1.],
        [ 1.,  1.],
        [ 1.,  1.],
        [ 1.,  1.]],

       [[ 1.,  1.],
        [ 1.,  1.],
        [ 1.,  1.],
        [ 1.,  1.]]])

One useful tool if the `flatten()` command, which will take in an array and return a 1-d version of it

In [7]:
random_array = np.arange(0,9).reshape(3,3)
random_array

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
random_array.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [11]:
random_array.flatten('F')

array([0, 3, 6, 1, 4, 7, 2, 5, 8])

In [12]:
random_array.flatten('F').shape #(9,) is just python's way of representing a tuple with 1 element

(9,)

You can flatten by going through each row first (default behavior), or by using `order = 'F'` or just `'F'` as an argument to specify column-first ('F' here stands for FORTRAN-style). For more information on this behavior, you can see the docs here:
https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.flatten.html

<a id='subsetting'></a>
### Subsetting 

Now that you know how to create `ndarray`s, you may want to access particular elements within an array. To do that, `numpy` offers various ways to slice arrays to your heart's content

In [23]:
a = np.array([1,2,3,4,5,6])
a = a.reshape((2,3))

In [25]:
a.shape[0], a.shape[1]

(2, 3)

In [55]:
a[3] # Access the 3rd element(Remember, python is 0-indexed) 

4

In [56]:
a[:3] # Elements up to the 3rd element

array([1, 2, 3])

In [59]:
a[3:] # 3rd element onwards

array([4, 5])

In [57]:
a[:-1] #Elements up to the last element

array([1, 2, 3, 4])

In [58]:
a[2:-1] # Combine the two

array([3, 4])

In [61]:
# 2-d Arrays
b = np.arange(0,9).reshape(3,3)
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [63]:
b[1,2] # first row, 2nd column

5

In [64]:
b[:, 2]  # Get all rows, and grab the 2nd value in each column

array([2, 5, 8])

In [67]:
b[b < 5] # Boolean indexing

array([0, 1, 2, 3, 4])

<a id='A_Note_on_Copying'></a>
## A Note on Copying

Be careful when copying numpy arrays. Assigning a new variable to an existing numpy array provides a view to that array, rather than actually copying the array. Here's a quick demonstration illustrating this.

In [26]:
# Let's create an array:

c = np.arange(0,9).reshape(3,3)
c

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [101]:
id(c) # here is the id() of the object c, which is essentially a universal identifier for that object

140472682714816

In [102]:
d = c

In [103]:
d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [104]:
id(d) # This is the same id!!! 

140472682714816

If I make a change to the array `c`, those changes will be propagated to `d`.

In [107]:
c.shape = (9,1)
c

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [108]:
d

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

To truly copy a numpy array, use the `np.copy()` method

In [112]:
e = np.arange(0,9).reshape(3,3)
f = e.copy() # Alternatively, f = np.copy(e)
e.shape = (9,1)
e

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [114]:
f # These are now different

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

<a id='aggregation'></a>
### Aggregation Functions
Numpy supports means, medians, standard deviations, etc across the entire array or just along a particular axis.

In [121]:
g = np.array(range(0, 100)).reshape(10,10)
g

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [122]:
g.mean()

49.5

In [123]:
g.mean(axis = 0) # Row-wise average

array([ 45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.])

In [125]:
g.mean(axis = 1) # Column-wise average

array([  4.5,  14.5,  24.5,  34.5,  44.5,  54.5,  64.5,  74.5,  84.5,  94.5])

In [128]:
g.cumsum(axis = 0) # Cumulative sum by row

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,  12,  14,  16,  18,  20,  22,  24,  26,  28],
       [ 30,  33,  36,  39,  42,  45,  48,  51,  54,  57],
       [ 60,  64,  68,  72,  76,  80,  84,  88,  92,  96],
       [100, 105, 110, 115, 120, 125, 130, 135, 140, 145],
       [150, 156, 162, 168, 174, 180, 186, 192, 198, 204],
       [210, 217, 224, 231, 238, 245, 252, 259, 266, 273],
       [280, 288, 296, 304, 312, 320, 328, 336, 344, 352],
       [360, 369, 378, 387, 396, 405, 414, 423, 432, 441],
       [450, 460, 470, 480, 490, 500, 510, 520, 530, 540]])

<a id='array_math'></a>
## Array Mathematics

As you might expect, numpy has built in functions for many array operations, such as matrix multiplication, transposes, eigenvalues, etc. In general, you can use python's built-in operators such as `+`, `-`, `*`, `/`. Alternatively, you can call `np.add`, `np.multiply`, etc. However, note that, unlike matlab, the `*` operator does not perform matrix multiplication. Instead, it is used for element-wise multiplication. `np.dot` is the correct operator for doing matrix multiplication

In [158]:
b = np.arange(0, 9).reshape(3,3)

In [159]:
h = np.arange(10, 19).reshape(3,3)
h

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [160]:
b + h

array([[10, 12, 14],
       [16, 18, 20],
       [22, 24, 26]])

In [161]:
# Or you can use np.add()
np.add(b, h)

array([[10, 12, 14],
       [16, 18, 20],
       [22, 24, 26]])

In [162]:
b / h # element-wise division

array([[ 0.        ,  0.09090909,  0.16666667],
       [ 0.23076923,  0.28571429,  0.33333333],
       [ 0.375     ,  0.41176471,  0.44444444]])

In [163]:
b * h # !!!!! element-wise multiplication

array([[  0,  11,  24],
       [ 39,  56,  75],
       [ 96, 119, 144]])

In [164]:
np.dot(b, h) # Matrix multiplication

array([[ 45,  48,  51],
       [162, 174, 186],
       [279, 300, 321]])

In [165]:
b.T # Transpose

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [166]:
np.sin(b)

array([[ 0.        ,  0.84147098,  0.90929743],
       [ 0.14112001, -0.7568025 , -0.95892427],
       [-0.2794155 ,  0.6569866 ,  0.98935825]])

`numpy` also has a linear algebra module for performing common linear algebra operations. A complete list of commands can be found in the docs: https://docs.scipy.org/doc/numpy/reference/routines.linalg.html

In [171]:
np.linalg.eig(h) # Returns a tuple of 2 arrays. The first is the eigenvalues, and the second is the eigenvectors

(array([  4.24242853e+01,  -4.24285286e-01,  -8.76087811e-16]),
 array([[-0.44819574, -0.73921067,  0.40824829],
        [-0.5688793 , -0.03327957, -0.81649658],
        [-0.68956285,  0.67265152,  0.40824829]]))

<a id='comparisons'></a>
## Comparisons

In [147]:
b

array([[0, 1, 2],
       [3, 4, 8],
       [6, 7, 8]])

In [149]:
i = np.ones((3,3))
i

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [150]:
b == i # Element-wise comparison -- returns array of the same shape

array([[False,  True, False],
       [False, False, False],
       [False, False, False]], dtype=bool)

In [151]:
b < i 

array([[ True, False, False],
       [False, False, False],
       [False, False, False]], dtype=bool)

In [152]:
b < 5

array([[ True,  True,  True],
       [ True,  True, False],
       [False, False, False]], dtype=bool)

In [153]:
np.array_equal(b, i)

False

In [157]:
i = np.arange(0,9).reshape(3,3)
i

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

<a id='combining'></a>
## Combining Arrays

One common array operation is to concatenate or stack arrays. Here are the most common ways to combine arrays together:

In [172]:
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [179]:
np.concatenate((b,b), axis = 0) # stacked b twice along the rows (axis = 0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [181]:
np.concatenate((b, b), axis = 1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [184]:
# alternatively, you can use hstack, which stands for Horizontal Stacking
np.hstack((b,b))

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [185]:
# Or Vstack
np.vstack((b,b))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

<a id='broadcasting'></a>
## Broadcasting and Vectorization

Broadcasting is a method that numpy and other numerical computation libraries in python such as `tensorflow` use to allow array functions to be applied to arrays with different shapes/sizes. Although broadcasting can seem initially confusing, it can often significantly decrease the amount of time needed to execute certain matrix operations. We'll see a few examples here, but this is by no means an exhaustive guide to broadcasting. To learn more about broadcasting, you can see the official documentation here: https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html

Generally, you can apply matrix arithmetic operations elementwise if the two arrays in question have the same `shape`

In [204]:
j = np.linspace(0, 8, 9).reshape(3,3)
j

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.]])

In [206]:
k = np.arange(0, 9).reshape(3,3)
k

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [208]:
# Array (3x3) + Array(3x3) = Array(3x3)
j + k

array([[  0.,   2.,   4.],
       [  6.,   8.,  10.],
       [ 12.,  14.,  16.]])

In [209]:
j * k

array([[  0.,   1.,   4.],
       [  9.,  16.,  25.],
       [ 36.,  49.,  64.]])

broadcasting allows for arrays of *different* sizes to undergo these operations as well. The simplest case of this is operations involving a scalar value.

In [210]:
l = 10

In [211]:
j + l

array([[ 10.,  11.,  12.],
       [ 13.,  14.,  15.],
       [ 16.,  17.,  18.]])

In [212]:
j * l

array([[  0.,  10.,  20.],
       [ 30.,  40.,  50.],
       [ 60.,  70.,  80.]])

In general, you can determine what the shape after an operation will be and whether or not a broadcasting operation is even possible according to the following rules:

1. If the arrays have the same rank, or number of dimensions, each dimension must either match, or be of size 1
2. If the arrays are not the same rank, pad the smaller array with a 1 starting from the left until the two arrays have the same dimension
3. If the dimensions are the same, apply the operation element-wise. If one of them is a 1, broadcast that operation across the other array along that dimension

Let's illustrate this with an example:

In [221]:
j

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.]])

In [222]:
j.shape

(3, 3)

In [218]:
m = np.linspace(0, 2, 3)

In [219]:
m

array([ 0.,  1.,  2.])

In [220]:
m.shape

(3,)

The array `j` has a shape of (3,3) and `m` has a shape of (3,). According to the rule, broadcasting an operation will pad `m` to be of size (1,3). The operation will then be broadcast as follows:

`j` (3x3)

`m` (1x3)

`result` (3x3)

In [223]:
j + m 

array([[  0.,   2.,   4.],
       [  3.,   5.,   7.],
       [  6.,   8.,  10.]])

In [225]:
j * m

array([[  0.,   1.,   4.],
       [  0.,   4.,  10.],
       [  0.,   7.,  16.]])

Here's a slightly more complicated example:

In [28]:
n = np.random.random((4,2,3,1))

In [29]:
o = np.arange(0, 12).reshape(3, 4)
o

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

The array `n` has a shape of (4,2,3,1) and `o` has a shape of (3,4). According to the rule, broadcasting an operation will pad `o` to be of size (1,1, 3, 4). The operation will then be broadcast as follows:

`n` (4x2x3x1)

`o` (1x1x3x4)

`result` (4x2x3x4)

In [236]:
(n + o).shape

(4, 2, 3, 4)

In [237]:
n + o

array([[[[  0.49317098,   1.49317098,   2.49317098,   3.49317098],
         [  4.51730879,   5.51730879,   6.51730879,   7.51730879],
         [  8.57372916,   9.57372916,  10.57372916,  11.57372916]],

        [[  0.04315109,   1.04315109,   2.04315109,   3.04315109],
         [  4.53756836,   5.53756836,   6.53756836,   7.53756836],
         [  8.15621357,   9.15621357,  10.15621357,  11.15621357]]],


       [[[  0.59000997,   1.59000997,   2.59000997,   3.59000997],
         [  4.45771489,   5.45771489,   6.45771489,   7.45771489],
         [  8.60054319,   9.60054319,  10.60054319,  11.60054319]],

        [[  0.0209099 ,   1.0209099 ,   2.0209099 ,   3.0209099 ],
         [  4.71987084,   5.71987084,   6.71987084,   7.71987084],
         [  8.23325026,   9.23325026,  10.23325026,  11.23325026]]],


       [[[  0.89498421,   1.89498421,   2.89498421,   3.89498421],
         [  4.45344758,   5.45344758,   6.45344758,   7.45344758],
         [  8.43509326,   9.43509326,  10.43509326

For a list of more examples, see the docs: https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html

## Vectorization

Numpy is fast mainly because of 2 things: 
 - Each `ndarray` has a known type, so no type checking has to occur
 - Operations can be vectorized

In [16]:
import math

test_vector = np.arange(0, 1000000)

In [17]:
%timeit [math.sqrt(x) for x in test_vector]

%timeit np.sqrt(test_vector)

222 ms ± 17.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
4.71 ms ± 83.1 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
